# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import drema_comm_pb2 as drema__comm__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in drema_comm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DremaInferenceServiceStub(object):
    """DREMA Dynamic Inference Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamFrames = channel.stream_unary(
                '/drema.DremaInferenceService/StreamFrames',
                request_serializer=drema__comm__pb2.FrameObservation.SerializeToString,
                response_deserializer=drema__comm__pb2.StreamStatus.FromString,
                _registered_method=True)
        self.SendFrame = channel.unary_unary(
                '/drema.DremaInferenceService/SendFrame',
                request_serializer=drema__comm__pb2.FrameObservation.SerializeToString,
                response_deserializer=drema__comm__pb2.StreamStatus.FromString,
                _registered_method=True)
        self.RequestAction = channel.unary_unary(
                '/drema.DremaInferenceService/RequestAction',
                request_serializer=drema__comm__pb2.RobotState.SerializeToString,
                response_deserializer=drema__comm__pb2.ControlAction.FromString,
                _registered_method=True)
        self.ResetEpisode = channel.unary_unary(
                '/drema.DremaInferenceService/ResetEpisode',
                request_serializer=drema__comm__pb2.ResetRequest.SerializeToString,
                response_deserializer=drema__comm__pb2.ResetResponse.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/drema.DremaInferenceService/Ping',
                request_serializer=drema__comm__pb2.PingRequest.SerializeToString,
                response_deserializer=drema__comm__pb2.PingResponse.FromString,
                _registered_method=True)


class DremaInferenceServiceServicer(object):
    """DREMA Dynamic Inference Service
    """

    def StreamFrames(self, request_iterator, context):
        """Streaming endpoint for sensor frames (f_cam ≈ 10-15 Hz)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendFrame(self, request, context):
        """Single-frame ingestion endpoint (alternative to stream for simpler stepped mode)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestAction(self, request, context):
        """High-frequency control query endpoint (f_ctrl ≈ 50 Hz)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetEpisode(self, request, context):
        """Episode lifecycle management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Connection check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DremaInferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamFrames': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamFrames,
                    request_deserializer=drema__comm__pb2.FrameObservation.FromString,
                    response_serializer=drema__comm__pb2.StreamStatus.SerializeToString,
            ),
            'SendFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.SendFrame,
                    request_deserializer=drema__comm__pb2.FrameObservation.FromString,
                    response_serializer=drema__comm__pb2.StreamStatus.SerializeToString,
            ),
            'RequestAction': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestAction,
                    request_deserializer=drema__comm__pb2.RobotState.FromString,
                    response_serializer=drema__comm__pb2.ControlAction.SerializeToString,
            ),
            'ResetEpisode': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetEpisode,
                    request_deserializer=drema__comm__pb2.ResetRequest.FromString,
                    response_serializer=drema__comm__pb2.ResetResponse.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=drema__comm__pb2.PingRequest.FromString,
                    response_serializer=drema__comm__pb2.PingResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'drema.DremaInferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('drema.DremaInferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DremaInferenceService(object):
    """DREMA Dynamic Inference Service
    """

    @staticmethod
    def StreamFrames(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/drema.DremaInferenceService/StreamFrames',
            drema__comm__pb2.FrameObservation.SerializeToString,
            drema__comm__pb2.StreamStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drema.DremaInferenceService/SendFrame',
            drema__comm__pb2.FrameObservation.SerializeToString,
            drema__comm__pb2.StreamStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drema.DremaInferenceService/RequestAction',
            drema__comm__pb2.RobotState.SerializeToString,
            drema__comm__pb2.ControlAction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetEpisode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drema.DremaInferenceService/ResetEpisode',
            drema__comm__pb2.ResetRequest.SerializeToString,
            drema__comm__pb2.ResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/drema.DremaInferenceService/Ping',
            drema__comm__pb2.PingRequest.SerializeToString,
            drema__comm__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
